// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsnqSYN6ik7J2PaLEd1jNvMYoIGk97sv8',
    appId: '1:827164927627:android:fd349168756d8e56c5168e',
    messagingSenderId: '827164927627',
    projectId: 'mobileappdevelopment-59505',
    storageBucket: 'mobileappdevelopment-59505.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5k6ICPL-omQ0w7eaBVYbPeINR2P53ns',
    appId: '1:827164927627:ios:8a1dcea064899094c5168e',
    messagingSenderId: '827164927627',
    projectId: 'mobileappdevelopment-59505',
    storageBucket: 'mobileappdevelopment-59505.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChikLOrlY5ZNMR2hmdCxqEsJXT3tbwa9E',
    appId: '1:827164927627:web:066b676118d43ad9c5168e',
    messagingSenderId: '827164927627',
    projectId: 'mobileappdevelopment-59505',
    authDomain: 'mobileappdevelopment-59505.firebaseapp.com',
    storageBucket: 'mobileappdevelopment-59505.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5k6ICPL-omQ0w7eaBVYbPeINR2P53ns',
    appId: '1:827164927627:ios:8a1dcea064899094c5168e',
    messagingSenderId: '827164927627',
    projectId: 'mobileappdevelopment-59505',
    storageBucket: 'mobileappdevelopment-59505.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChikLOrlY5ZNMR2hmdCxqEsJXT3tbwa9E',
    appId: '1:827164927627:web:879027ba622ba3e6c5168e',
    messagingSenderId: '827164927627',
    projectId: 'mobileappdevelopment-59505',
    authDomain: 'mobileappdevelopment-59505.firebaseapp.com',
    storageBucket: 'mobileappdevelopment-59505.firebasestorage.app',
  );

}